display_name: vyavasaay
package_name: vyavasaay

maintainer:
  name: Himanshu Chaurasiya
  email: himanshuchaurasiya24@gmail.com

priority: optional

section: x11

installed_size: 15700

dependencies:
  - mpv
  - libsqlite3
  - libsqlite3-dev

essential: false

icon: assets/app_icon.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - vyavasaay
  - vyavasaay

generic_name: vyavasaay

categories:
  - Finance
  - Accounting

startup_notify: true