name: vyavasaay
version: 1.0.0
summary: A Diagnostic Center Management Software
description: This is a free software project under development which will help diagnostic centre in managing their lab activity like report generation, doctors incentive with graded access control to admin and the technician.We require you not to fully depend on it as it is under development and to keep a back up of your center report on other sources.

confinement: strict
base: core22
grade: stable

slots:
  dbus-vyavasaay: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.example # adjust accordingly to your app name and

apps:
  vyavasaay:
    command: vyavasaay
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
      - network
    slots:
      - dbus-vyavasaay
parts:
  vyavasaay:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application